version: "2"
run:
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - gocognit
    - lll
    - nlreturn
  settings:
    funlen:
      lines: 120
      statements: 70
    lll:
      line-length: 135
    nolintlint:
      require-explanation: true
      require-specific: true
    paralleltest:
      ignore-missing: true
    varnamelen:
      max-distance: 10
      ignore-names:
        - err
        - wg
        - ch
        - in
        - out
        - tt
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mcgillowen/arkime-kafka-indexer)
        - blank
        - dot
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
