run:
  modules-download-mode: readonly
  timeout: 2m

linters-settings:
  varnamelen:
    max-distance: 10
    ignore-names:
      - err
      - wg
      - ch
      - in
      - out
      - tt
  funlen:
    lines: 120
    statements: 70
  lll:
    line-length: 135
  nolintlint:
    require-explanation: true
    require-specific: true
  paralleltest:
    ignore-missing: true
  gci:
    skip-generated: true
    sections:
      - standard
      - default
      - prefix(github.com/mcgillowen/arkime-kafka-indexer)
      - blank
      - dot

issues:
  exclude-files:
    - version.go
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - dupl

linters:
  enable-all: true

  disable:
    - exhaustruct
    - nlreturn
    - cyclop
    - gocognit
    - lll
    - depguard
    - exportloopref # Deprecated
