# Make sure to check the documentation at https://goreleaser.com
version: 2

git:
  prerelease_suffix: "-"

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-s -w"
      - "-X github.com/prometheus/common/version.Version={{.Version}}"
      - "-X github.com/prometheus/common/version.Revision={{.FullCommit}}"
      - "-X github.com/prometheus/common/version.BuildDate={{.Date}}"
      - "-X github.com/prometheus/common/version.BuildUser=goreleaser"
    flags:
      - -trimpath
    tags:
      - netgo
    mod_timestamp: '{{ .CommitTimestamp }}'
    overrides:
      - goos: linux
        goarch: amd64
        goamd64: v1
        env:
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++

dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    goamd64: v1
    image_templates:
      - "ghcr.io/mcgillowen/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/mcgillowen/{{ .ProjectName }}:latest"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"


archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto
  github:
    owner: mcgillowen
    name: arkime-kafka-indexer

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
