name: Go

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['stable']
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Check dependencies are tidy
        uses: katexochen/go-tidy-check@427c8c07d3d83ab8d7290cad04ce71c12eab3674

      - name: Install tools
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Install dependencies
        run: |
          go mod download

      - name: Verify dependencies
        run: |
          go mod verify

      - name: Run govulncheck
        run: |
          govulncheck -test ./...

      - name: Build
        run: |
          go build -v -o /dev/null ./...

      - name: Test with Go
        run: |
          go test -v -json -race -shuffle=on -coverprofile=coverage-${{ matrix.go-version }}.txt ./... > TestResults-${{ matrix.go-version }}.json

      - name: Upload Go test results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: Go-${{ matrix.go-version }}-results
          path: TestResults-${{ matrix.go-version }}.json

      - name: Upload Coverage
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac
        continue-on-error: true  # we don't care if it fails
        with:
          files: ./coverage-${{ matrix.go-version }}.txt  # file from the previous step
          fail_ci_if_error: false
  
